name: samurai-mpi-2-env
channels:
  - conda-forge
dependencies:
  - cmake
  - ninja
  - xtensor>0.25
  - highfive>=3.0
  - fmt
  - pugixml
  - cli11<2.5
  - pytest
  #- h5py
  - "h5py=*=mpi_*"
  - libboost-mpi #<1.87 # MPI seems broken with 1.87 with the error : symbol not found in flat namespace '_PyBaseObject_Type'
  - libboost-devel
  - libboost-headers
  #- hdf5 * mpi_*
  - "hdf5=*=mpi_*"
  - mpich
