name: samurai-env
channels:
  - conda-forge
dependencies:
  - cmake
  - ninja
  - xtensor<0.26
  - highfive
  - fmt
  - pugixml
  - cxxopts
  - cli11<2.5
  - pytest
  - h5py
  - libboost-mpi #<1.87 # MPI seems broken with 1.87 with the error : symbol not found in flat namespace '_PyBaseObject_Type'
  - libboost-devel
  - libboost-headers
  - hdf5=*=mpi*
  - mpich
